//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.7.6, generator: @autorest/go@4.0.0-preview.42)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package generated

// BackupClientCancelResponse contains the response from method BackupClient.Cancel.
type BackupClientCancelResponse struct {
	BackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// BackupClientGetResponse contains the response from method BackupClient.Get.
type BackupClientGetResponse struct {
	BackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// BackupClientRefreshTokensResponse contains the response from method BackupClient.RefreshTokens.
type BackupClientRefreshTokensResponse struct {
	BackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// CommitOrRollbackBackupClientCancelResponse contains the response from method CommitOrRollbackBackupClient.Cancel.
type CommitOrRollbackBackupClientCancelResponse struct {
	CommitOrRollbackBackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// CommitOrRollbackBackupClientGetResponse contains the response from method CommitOrRollbackBackupClient.Get.
type CommitOrRollbackBackupClientGetResponse struct {
	CommitOrRollbackBackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// CommitOrRollbackBackupClientRefreshTokensResponse contains the response from method CommitOrRollbackBackupClient.RefreshTokens.
type CommitOrRollbackBackupClientRefreshTokensResponse struct {
	CommitOrRollbackBackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// CommitOrRollbackRestoreClientCancelResponse contains the response from method CommitOrRollbackRestoreClient.Cancel.
type CommitOrRollbackRestoreClientCancelResponse struct {
	CommitOrRollbackRestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// CommitOrRollbackRestoreClientGetResponse contains the response from method CommitOrRollbackRestoreClient.Get.
type CommitOrRollbackRestoreClientGetResponse struct {
	CommitOrRollbackRestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// CommitOrRollbackRestoreClientRefreshTokensResponse contains the response from method CommitOrRollbackRestoreClient.RefreshTokens.
type CommitOrRollbackRestoreClientRefreshTokensResponse struct {
	CommitOrRollbackRestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientBackupResponse contains the response from method PluginClient.Backup.
type PluginClientBackupResponse struct {
	BackupResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientCommitOrRollbackBackupResponse contains the response from method PluginClient.CommitOrRollbackBackup.
type PluginClientCommitOrRollbackBackupResponse struct {
	CommitOrRollbackBackupResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientCommitOrRollbackRestoreResponse contains the response from method PluginClient.CommitOrRollbackRestore.
type PluginClientCommitOrRollbackRestoreResponse struct {
	CommitOrRollbackRestoreResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientRestoreResponse contains the response from method PluginClient.Restore.
type PluginClientRestoreResponse struct {
	RestoreResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientStartProtectionResponse contains the response from method PluginClient.StartProtection.
type PluginClientStartProtectionResponse struct {
	StartProtectionResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientStopProtectionResponse contains the response from method PluginClient.StopProtection.
type PluginClientStopProtectionResponse struct {
	StopProtectionResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientUpdateProtectionResponse contains the response from method PluginClient.UpdateProtection.
type PluginClientUpdateProtectionResponse struct {
	UpdateProtectionResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientValidateForBackupResponse contains the response from method PluginClient.ValidateForBackup.
type PluginClientValidateForBackupResponse struct {
	ValidateForBackupResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientValidateForProtectionResponse contains the response from method PluginClient.ValidateForProtection.
type PluginClientValidateForProtectionResponse struct {
	ValidateForProtectionResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// PluginClientValidateForRestoreResponse contains the response from method PluginClient.ValidateForRestore.
type PluginClientValidateForRestoreResponse struct {
	ValidateForRestoreResponse
	// OperationLocation contains the information returned from the Operation-Location header response.
	OperationLocation *string

	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// RestoreClientCancelResponse contains the response from method RestoreClient.Cancel.
type RestoreClientCancelResponse struct {
	RestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// RestoreClientGetResponse contains the response from method RestoreClient.Get.
type RestoreClientGetResponse struct {
	RestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// RestoreClientRefreshTokensResponse contains the response from method RestoreClient.RefreshTokens.
type RestoreClientRefreshTokensResponse struct {
	RestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// StartProtectionClientCancelResponse contains the response from method StartProtectionClient.Cancel.
type StartProtectionClientCancelResponse struct {
	StartProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// StartProtectionClientGetResponse contains the response from method StartProtectionClient.Get.
type StartProtectionClientGetResponse struct {
	StartProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// StartProtectionClientRefreshTokensResponse contains the response from method StartProtectionClient.RefreshTokens.
type StartProtectionClientRefreshTokensResponse struct {
	StartProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// StopProtectionClientCancelResponse contains the response from method StopProtectionClient.Cancel.
type StopProtectionClientCancelResponse struct {
	StopProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// StopProtectionClientGetResponse contains the response from method StopProtectionClient.Get.
type StopProtectionClientGetResponse struct {
	StopProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// StopProtectionClientRefreshTokensResponse contains the response from method StopProtectionClient.RefreshTokens.
type StopProtectionClientRefreshTokensResponse struct {
	StopProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// UpdateProtectionClientCancelResponse contains the response from method UpdateProtectionClient.Cancel.
type UpdateProtectionClientCancelResponse struct {
	UpdateProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// UpdateProtectionClientGetResponse contains the response from method UpdateProtectionClient.Get.
type UpdateProtectionClientGetResponse struct {
	UpdateProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// UpdateProtectionClientRefreshTokensResponse contains the response from method UpdateProtectionClient.RefreshTokens.
type UpdateProtectionClientRefreshTokensResponse struct {
	UpdateProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForBackupClientCancelResponse contains the response from method ValidateForBackupClient.Cancel.
type ValidateForBackupClientCancelResponse struct {
	ValidateForBackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForBackupClientGetResponse contains the response from method ValidateForBackupClient.Get.
type ValidateForBackupClientGetResponse struct {
	ValidateForBackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForBackupClientRefreshTokensResponse contains the response from method ValidateForBackupClient.RefreshTokens.
type ValidateForBackupClientRefreshTokensResponse struct {
	ValidateForBackupResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForProtectionClientCancelResponse contains the response from method ValidateForProtectionClient.Cancel.
type ValidateForProtectionClientCancelResponse struct {
	ValidateForProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForProtectionClientGetResponse contains the response from method ValidateForProtectionClient.Get.
type ValidateForProtectionClientGetResponse struct {
	ValidateForProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForProtectionClientRefreshTokensResponse contains the response from method ValidateForProtectionClient.RefreshTokens.
type ValidateForProtectionClientRefreshTokensResponse struct {
	ValidateForProtectionResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForRestoreClientCancelResponse contains the response from method ValidateForRestoreClient.Cancel.
type ValidateForRestoreClientCancelResponse struct {
	ValidateForRestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForRestoreClientGetResponse contains the response from method ValidateForRestoreClient.Get.
type ValidateForRestoreClientGetResponse struct {
	ValidateForRestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

// ValidateForRestoreClientRefreshTokensResponse contains the response from method ValidateForRestoreClient.RefreshTokens.
type ValidateForRestoreClientRefreshTokensResponse struct {
	ValidateForRestoreResponse
	// RetryAfter contains the information returned from the Retry-After header response.
	RetryAfter *int32

	// XMSErrorCode contains the information returned from the x-ms-error-code header response.
	XMSErrorCode *string

	// XMSRequestID contains the information returned from the x-ms-request-id header response.
	XMSRequestID *string
}

